### ISSUE TITLE
Internal error after moving class

### ISSUE THREAD

**Issue by paulvi** [stuarthendren/jdt.spelling#43] opened 2014-12-09 10:20 UTC
I was moving class to other package, then toniced

```
org.eclipse.core.internal.resources.ResourceException: Resource '/MariaSearch/src/com/funshion/mariasearch/MainActivity.java' does not exist.
	at org.eclipse.core.internal.resources.Resource.checkExists(Resource.java:341)
	at org.eclipse.core.internal.resources.Resource.checkAccessible(Resource.java:215)
	at org.eclipse.core.internal.resources.Resource.deleteMarkers(Resource.java:846)
	at jdt.spelling.marker.MarkerFactory.clear(MarkerFactory.java:65)
	at jdt.spelling.processor.Processor.prepare(Processor.java:40)
	at jdt.spelling.processor.Processor.access$0(Processor.java:39)
	at jdt.spelling.processor.Processor$1.run(Processor.java:26)
	at jdt.spelling.marker.MarkerJob.runInWorkspace(MarkerJob.java:29)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:38)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

eclipse.buildId=4.4.0.I20140606-1215
java.version=1.8.0_05
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh_CN
Framework arguments:  -product org.eclipse.epp.package.standard.product -showLocation
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.standard.product -showLocation

**Comment by stuarthendren** [comment] 2015-01-25 15:08
Duplicate of #42

**Closed by stuarthendren** 2015-01-25 15:08 UTC
